### ISSUE TITLE
Error on ImtelliJ 14.1 EAP

### ISSUE THREAD

**Issue by bric3** [ukcrpb6/guava-postfix-plugin#19] opened 2015-02-17 18:40 UTC
Hi, thank you very much for the plugin and the recent update.

For information it seems the jetbrains guys changed the post fix plugin API in 14.1, hence this plugin  fails with the following stacktrace. It seems the constructor of `PostfixTemplateWithExpressionSelector` has changed.

```
com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.<init>(Ljava/lang/String;Ljava/lang/String;Lcom/intellij/codeInsight/template/postfix/templates/PostfixTemplatePsiInfo;Lcom/intellij/openapi/util/Condition;)V
java.lang.NoSuchMethodError: com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.<init>(Ljava/lang/String;Ljava/lang/String;Lcom/intellij/codeInsight/template/postfix/templates/PostfixTemplatePsiInfo;Lcom/intellij/openapi/util/Condition;)V
	at uk.co.drache.intellij.codeinsight.postfix.internal.RichTopmostStringBasedPostfixTemplate.<init>(RichTopmostStringBasedPostfixTemplate.java:46)
	at uk.co.drache.intellij.codeinsight.postfix.templates.CheckArgumentPostfixTemplate.<init>(CheckArgumentPostfixTemplate.java:37)
	at uk.co.drache.intellij.codeinsight.postfix.GuavaPostfixTemplateProvider.<init>(GuavaPostfixTemplateProvider.java:52)
	at sun.reflect.GeneratedConstructorAccessor662.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:68)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:36)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:38)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:26)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:71)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.isApplicable(PostfixLiveTemplate.java:163)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.isApplicable(TemplateManagerImpl.java:309)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.listApplicableCustomTemplates(TemplateManagerImpl.java:578)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.a(LiveTemplateCompletionContributor.java:152)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$100(LiveTemplateCompletionContributor.java:50)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:98)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:154)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:115)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:787)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$1000(CompletionProgressIndicator.java:89)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:769)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1$1.run(CompletionThreading.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at com.intellij.codeInsight.completion.AsyncCompletion$1$1.run(CompletionThreading.java:88)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:451)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:401)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:136)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.run(CompletionThreading.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by ukcrpb6** [comment] 2015-02-20 20:43
I suspect this is a duplicate of #18 - https://github.com/ukcrpb6/guava-postfix-plugin/releases/tag/v1.1.1alpha

Am getting the latest EAP to make sure there are everything is still stable.

**Comment by ukcrpb6** [comment] 2015-02-20 21:41
Verified, this alpha release is still functional under 140.2493.5.

**Comment by bric3** [comment] 2015-02-20 21:41
Hi this is indeed the same issue, API has changed

**Closed by ukcrpb6** 2015-02-20 21:41 UTC

**Comment by bric3** [comment] 2015-02-20 21:42
Hi cool, anyway nothing to hurry up it's an EAP after all.

Issues are kinda expected ;)
